import { useState, useMemo } from "react";
import {
    Building2,
    Plus,
    Edit3,
    Trash2,
    Loader2,
    X,
    Search,
    Users,
    AlertTriangle,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { SearchableSelect } from "@/components/ui/SearchableSelect";
import { useDepartments, useCostCentres, useEmployees } from "@/features/company-admin/api/use-hr-queries";
import {
    useCreateDepartment,
    useUpdateDepartment,
    useDeleteDepartment,
} from "@/features/company-admin/api/use-hr-mutations";
import { SkeletonTable } from "@/components/ui/Skeleton";
import { EmptyState } from "@/components/ui/EmptyState";
import { showSuccess, showApiError } from "@/lib/toast";

/* ── Shared form atoms ── */

function FormField({
    label,
    value,
    onChange,
    placeholder,
    type = "text",
    disabled = false,
}: {
    label: string;
    value: string;
    onChange: (v: string) => void;
    placeholder?: string;
    type?: string;
    disabled?: boolean;
}) {
    return (
        <div>
            <label className="block text-xs font-semibold text-neutral-500 dark:text-neutral-400 uppercase tracking-wider mb-1.5">
                {label}
            </label>
            <input
                type={type}
                value={value}
                onChange={(e) => onChange(e.target.value)}
                placeholder={placeholder}
                disabled={disabled}
                className={cn(
                    "w-full px-3 py-2.5 bg-neutral-50 dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 dark:text-white placeholder:text-neutral-400 transition-all",
                    disabled && "opacity-50 cursor-not-allowed"
                )}
            />
        </div>
    );
}

function SelectField({
    label,
    value,
    onChange,
    options,
    placeholder,
}: {
    label: string;
    value: string;
    onChange: (v: string) => void;
    options: { value: string; label: string }[];
    placeholder?: string;
}) {
    return (
        <div>
            <label className="block text-xs font-semibold text-neutral-500 dark:text-neutral-400 uppercase tracking-wider mb-1.5">
                {label}
            </label>
            <select
                value={value}
                onChange={(e) => onChange(e.target.value)}
                className="w-full px-3 py-2.5 bg-neutral-50 dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 dark:text-white transition-all"
            >
                <option value="">{placeholder ?? "Select..."}</option>
                {options.map((o) => (
                    <option key={o.value} value={o.value}>
                        {o.label}
                    </option>
                ))}
            </select>
        </div>
    );
}

function StatusBadge({ status }: { status: string }) {
    const active = status?.toLowerCase() === "active";
    return (
        <span
            className={cn(
                "text-[10px] font-bold px-2 py-0.5 rounded-full border",
                active
                    ? "bg-success-50 text-success-700 border-success-200 dark:bg-success-900/20 dark:text-success-400 dark:border-success-800/50"
                    : "bg-neutral-100 text-neutral-600 border-neutral-200 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-700"
            )}
        >
            {status}
        </span>
    );
}

/* ── Empty form ── */

const EMPTY_DEPT = {
    name: "",
    code: "",
    parentId: "",
    headEmployeeId: "",
    costCentreCode: "",
    status: "Active",
};

/* ── Screen ── */

export function DepartmentScreen() {
    const { data, isLoading, isError } = useDepartments();
    const costCentresQuery = useCostCentres();
    const createMutation = useCreateDepartment();
    const updateMutation = useUpdateDepartment();
    const deleteMutation = useDeleteDepartment();

    const empQuery = useEmployees();

    const [search, setSearch] = useState("");
    const [modalOpen, setModalOpen] = useState(false);
    const [editingId, setEditingId] = useState<string | null>(null);
    const [form, setForm] = useState({ ...EMPTY_DEPT });
    const [deleteTarget, setDeleteTarget] = useState<any>(null);
    const [codeAutoGenerated, setCodeAutoGenerated] = useState(true);

    const departments: any[] = data?.data ?? [];
    const costCentres: any[] = costCentresQuery.data?.data ?? [];
    const employees: any[] = (empQuery.data as any)?.data ?? [];

    const employeeOptions = useMemo(() =>
        employees.map((emp: any) => ({
            value: emp.id,
            label: `${emp.firstName} ${emp.lastName}`,
            sublabel: emp.employeeId,
        })),
        [employees]
    );

    const filtered = departments.filter((d: any) => {
        if (!search) return true;
        const s = search.toLowerCase();
        return (
            d.name?.toLowerCase().includes(s) ||
            d.code?.toLowerCase().includes(s)
        );
    });

    const openCreate = () => {
        setEditingId(null);
        setForm({ ...EMPTY_DEPT });
        setCodeAutoGenerated(true);
        setModalOpen(true);
    };

    const openEdit = (dept: any) => {
        setEditingId(dept.id);
        setForm({
            name: dept.name ?? "",
            code: dept.code ?? "",
            parentId: dept.parentId ?? "",
            headEmployeeId: dept.headEmployeeId ?? "",
            costCentreCode: dept.costCentreCode ?? "",
            status: dept.status ?? "Active",
        });
        setCodeAutoGenerated(false);
        setModalOpen(true);
    };

    const handleSave = async () => {
        try {
            const payload: Record<string, any> = {
                name: form.name,
                code: form.code,
                status: form.status,
            };
            if (form.parentId) payload.parentId = form.parentId;
            if (form.headEmployeeId) payload.headEmployeeId = form.headEmployeeId;
            if (form.costCentreCode) payload.costCentreCode = form.costCentreCode;

            if (editingId) {
                await updateMutation.mutateAsync({ id: editingId, data: payload });
                showSuccess("Department Updated", `${form.name} has been updated.`);
            } else {
                await createMutation.mutateAsync(payload);
                showSuccess("Department Created", `${form.name} has been added.`);
            }
            setModalOpen(false);
        } catch (err) {
            showApiError(err);
        }
    };

    const handleDelete = async () => {
        if (!deleteTarget) return;
        try {
            await deleteMutation.mutateAsync(deleteTarget.id);
            showSuccess("Department Deleted", `${deleteTarget.name} has been removed.`);
            setDeleteTarget(null);
        } catch (err) {
            showApiError(err);
        }
    };

    const saving = createMutation.isPending || updateMutation.isPending;
    const updateField = (key: string, value: any) => setForm((p) => ({ ...p, [key]: value }));

    const generateCode = (name: string): string => {
        if (!name.trim()) return "";
        const words = name.trim().split(/\s+/);
        const abbr = words.length >= 2
            ? words.map(w => w[0]!.toUpperCase()).join("").slice(0, 4)
            : name.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 4);
        return `${abbr}-001`;
    };

    const handleNameChange = (name: string) => {
        updateField('name', name);
        if (codeAutoGenerated && !editingId) {
            updateField('code', generateCode(name));
        }
    };

    const handleCodeChange = (code: string) => {
        updateField('code', code);
        setCodeAutoGenerated(false);
    };

    const parentName = (id: string) => departments.find((d: any) => d.id === id)?.name ?? "—";
    const headEmployeeName = (id: string) => {
        const emp = employees.find((e: any) => e.id === id);
        return emp ? `${emp.firstName} ${emp.lastName}` : "—";
    };

    return (
        <div className="space-y-6 animate-in fade-in duration-500">
            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold text-primary-950 dark:text-white tracking-tight">Departments</h1>
                    <p className="text-neutral-500 dark:text-neutral-400 mt-1">Manage organisational departments</p>
                </div>
                <button
                    onClick={openCreate}
                    className="inline-flex items-center gap-2 bg-primary-600 hover:bg-primary-700 text-white px-5 py-2.5 rounded-xl font-bold text-sm shadow-md shadow-primary-500/20 transition-all dark:shadow-none"
                >
                    <Plus className="w-5 h-5" />
                    Add Department
                </button>
            </div>

            {/* Toolbar */}
            <div className="bg-white dark:bg-neutral-900 p-4 rounded-2xl border border-neutral-200/60 dark:border-neutral-800 shadow-sm">
                <div className="relative max-w-md w-full">
                    <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-5 h-5 text-neutral-400 dark:text-neutral-500" />
                    <input
                        type="text"
                        placeholder="Search departments..."
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="w-full pl-11 pr-4 py-2.5 bg-neutral-50 dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 dark:text-white placeholder:text-neutral-400 transition-all"
                    />
                </div>
            </div>

            {isError && (
                <div className="bg-danger-50 dark:bg-danger-900/20 border border-danger-200 dark:border-danger-800/50 rounded-xl p-4 text-sm text-danger-700 dark:text-danger-400 font-medium">
                    Failed to load departments. Please try again.
                </div>
            )}

            {/* Data Table */}
            <div className="bg-white dark:bg-neutral-900 rounded-2xl border border-neutral-200/60 dark:border-neutral-800 shadow-xl shadow-neutral-900/5 overflow-hidden">
                {isLoading ? (
                    <SkeletonTable rows={5} cols={7} />
                ) : (
                    <div className="overflow-x-auto">
                        <table className="w-full text-left border-collapse min-w-[950px]">
                            <thead>
                                <tr className="bg-neutral-50/50 dark:bg-neutral-800/30 border-b border-neutral-200 dark:border-neutral-800 text-xs text-neutral-500 dark:text-neutral-400 uppercase tracking-widest">
                                    <th className="py-4 px-6 font-bold">Name</th>
                                    <th className="py-4 px-6 font-bold">Code</th>
                                    <th className="py-4 px-6 font-bold">Parent</th>
                                    <th className="py-4 px-6 font-bold">Head</th>
                                    <th className="py-4 px-6 font-bold">Cost Centre</th>
                                    <th className="py-4 px-6 font-bold text-center">Status</th>
                                    <th className="py-4 px-6 font-bold text-center">Employees</th>
                                    <th className="py-4 px-6 font-bold text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="text-sm">
                                {filtered.map((dept: any) => (
                                    <tr
                                        key={dept.id}
                                        className="border-b border-neutral-100 dark:border-neutral-800/50 last:border-0 hover:bg-neutral-50/50 dark:hover:bg-neutral-800/50 transition-colors"
                                    >
                                        <td className="py-4 px-6">
                                            <div className="flex items-center gap-3">
                                                <div className="w-8 h-8 rounded-lg bg-primary-50 dark:bg-primary-900/30 flex items-center justify-center shrink-0">
                                                    <Building2 className="w-4 h-4 text-primary-600 dark:text-primary-400" />
                                                </div>
                                                <span className="font-bold text-primary-950 dark:text-white">{dept.name}</span>
                                            </div>
                                        </td>
                                        <td className="py-4 px-6 font-mono text-xs text-neutral-600 dark:text-neutral-400">{dept.code || "—"}</td>
                                        <td className="py-4 px-6 text-neutral-600 dark:text-neutral-400">{parentName(dept.parentId)}</td>
                                        <td className="py-4 px-6 text-neutral-600 dark:text-neutral-400">{headEmployeeName(dept.headEmployeeId)}</td>
                                        <td className="py-4 px-6 font-mono text-xs text-neutral-600 dark:text-neutral-400">{dept.costCentreCode || "—"}</td>
                                        <td className="py-4 px-6 text-center">
                                            <StatusBadge status={dept.status ?? "Active"} />
                                        </td>
                                        <td className="py-4 px-6 text-center">
                                            <div className="inline-flex items-center gap-1.5">
                                                <Users size={13} className="text-neutral-400" />
                                                <span className="font-semibold text-primary-950 dark:text-white">{dept.employeeCount ?? 0}</span>
                                            </div>
                                        </td>
                                        <td className="py-4 px-6 text-right">
                                            <div className="flex items-center justify-end gap-1">
                                                <button onClick={() => openEdit(dept)} className="p-2 text-primary-600 dark:text-primary-400 hover:bg-primary-50 dark:hover:bg-primary-900/30 rounded-lg transition-colors" title="Edit">
                                                    <Edit3 size={15} />
                                                </button>
                                                <button onClick={() => setDeleteTarget(dept)} className="p-2 text-danger-500 hover:bg-danger-50 dark:hover:bg-danger-900/20 rounded-lg transition-colors" title="Delete">
                                                    <Trash2 size={15} />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                                {filtered.length === 0 && !isLoading && (
                                    <tr>
                                        <td colSpan={8}>
                                            <EmptyState icon="list" title="No departments found" message="Add your first department to get started." action={{ label: "Add Department", onClick: openCreate }} />
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>

            {/* ── Create/Edit Modal ── */}
            {modalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
                    <div className="bg-white dark:bg-neutral-900 rounded-3xl shadow-2xl w-full max-w-lg animate-in fade-in zoom-in-95 duration-200 flex flex-col max-h-[90vh]">
                        <div className="flex items-center justify-between px-6 py-4 border-b border-neutral-100 dark:border-neutral-800">
                            <h2 className="text-lg font-bold text-primary-950 dark:text-white">{editingId ? "Edit Department" : "Add Department"}</h2>
                            <button onClick={() => setModalOpen(false)} className="p-1.5 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-800 text-neutral-400 transition-colors">
                                <X size={18} />
                            </button>
                        </div>
                        <div className="p-6 overflow-y-auto flex-1 space-y-4">
                            <FormField label="Department Name" value={form.name} onChange={handleNameChange} placeholder="e.g. Engineering" />
                            <FormField label="Code" value={form.code} onChange={handleCodeChange} placeholder="e.g. ENG" />
                            <SelectField
                                label="Parent Department"
                                value={form.parentId}
                                onChange={(v) => updateField("parentId", v)}
                                placeholder="None (Top Level)"
                                options={departments
                                    .filter((d: any) => d.id !== editingId)
                                    .map((d: any) => ({ value: d.id, label: d.name }))}
                            />
                            <SearchableSelect
                                label="Department Head"
                                value={form.headEmployeeId}
                                onChange={(v) => updateField("headEmployeeId", v)}
                                options={employeeOptions}
                                placeholder="Search employee..."
                            />
                            <SelectField
                                label="Cost Centre"
                                value={form.costCentreCode}
                                onChange={(v) => updateField("costCentreCode", v)}
                                placeholder="Select cost centre..."
                                options={costCentres.map((c: any) => ({ value: c.code ?? c.id, label: `${c.code} - ${c.name}` }))}
                            />
                            <SelectField
                                label="Status"
                                value={form.status}
                                onChange={(v) => updateField("status", v)}
                                options={[
                                    { value: "Active", label: "Active" },
                                    { value: "Inactive", label: "Inactive" },
                                ]}
                            />
                        </div>
                        <div className="flex gap-3 px-6 py-4 border-t border-neutral-100 dark:border-neutral-800">
                            <button onClick={() => setModalOpen(false)} className="flex-1 py-2.5 rounded-xl border border-neutral-200 dark:border-neutral-700 text-sm font-bold text-neutral-700 dark:text-neutral-300 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors">Cancel</button>
                            <button onClick={handleSave} disabled={saving} className="flex-1 py-2.5 rounded-xl bg-primary-600 hover:bg-primary-700 text-white text-sm font-bold transition-colors disabled:opacity-50 flex items-center justify-center gap-2">
                                {saving && <Loader2 size={14} className="animate-spin" />}
                                {saving ? "Saving..." : editingId ? "Update" : "Create"}
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* ── Delete Confirmation ── */}
            {deleteTarget && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
                    <div className="bg-white dark:bg-neutral-900 rounded-3xl shadow-2xl w-full max-w-sm p-7 animate-in fade-in zoom-in-95 duration-200">
                        <h2 className="text-lg font-bold text-danger-700 dark:text-danger-400 mb-2">Delete Department?</h2>
                        {(deleteTarget.employeeCount ?? 0) > 0 ? (
                            <>
                                <div className="flex items-start gap-3 p-3 bg-warning-50 dark:bg-warning-900/20 border border-warning-200 dark:border-warning-800/50 rounded-xl mb-4">
                                    <AlertTriangle size={18} className="text-warning-600 dark:text-warning-400 mt-0.5 shrink-0" />
                                    <p className="text-sm text-warning-700 dark:text-warning-400">
                                        This department has <strong>{deleteTarget.employeeCount}</strong> employee(s) assigned. Please reassign them before deleting.
                                    </p>
                                </div>
                                <div className="flex gap-3">
                                    <button onClick={() => setDeleteTarget(null)} className="flex-1 py-3 rounded-xl border border-neutral-200 dark:border-neutral-700 text-sm font-bold text-neutral-700 dark:text-neutral-300 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors">Close</button>
                                </div>
                            </>
                        ) : (
                            <>
                                <p className="text-sm text-neutral-500 dark:text-neutral-400">
                                    This will permanently delete <strong>{deleteTarget.name}</strong>. This action cannot be undone.
                                </p>
                                <div className="flex gap-3 mt-6">
                                    <button onClick={() => setDeleteTarget(null)} className="flex-1 py-3 rounded-xl border border-neutral-200 dark:border-neutral-700 text-sm font-bold text-neutral-700 dark:text-neutral-300 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors">Cancel</button>
                                    <button onClick={handleDelete} disabled={deleteMutation.isPending} className="flex-1 py-3 rounded-xl bg-danger-600 hover:bg-danger-700 text-white text-sm font-bold transition-colors disabled:opacity-50">
                                        {deleteMutation.isPending ? "Deleting..." : "Delete"}
                                    </button>
                                </div>
                            </>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
