export {
    companyAdminKeys,
    useCompanyProfile,
    useCompanyLocations,
    useCompanyLocation,
    useCompanyShifts,
    useCompanyContacts,
    useCompanyNoSeries,
    useCompanyIOTReasons,
    useCompanyControls,
    useCompanySettings,
    useCompanyUsers,
    useCompanyUser,
    useCompanyAuditLogs,
    useCompanyActivity,
    useRbacRoles,
} from './use-company-admin-queries';

export {
    useUpdateProfileSection,
    useUpdateLocation,
    useDeleteLocation,
    useCreateShift,
    useUpdateShift,
    useDeleteShift,
    useCreateContact,
    useUpdateContact,
    useDeleteContact,
    useCreateNoSeries,
    useUpdateNoSeries,
    useDeleteNoSeries,
    useCreateIOTReason,
    useUpdateIOTReason,
    useDeleteIOTReason,
    useUpdateControls,
    useUpdateSettings,
    useCreateUser,
    useUpdateUser,
    useUpdateUserStatus,
    useCreateRole,
    useUpdateRole,
    useDeleteRole,
} from './use-company-admin-mutations';

export {
    hrKeys,
    useDepartments,
    useDepartment,
    useDesignations,
    useDesignation,
    useGrades,
    useGrade,
    useEmployeeTypes,
    useEmployeeType,
    useCostCentres,
    useCostCentre,
    useEmployees,
    useEmployee,
    useEmployeeNominees,
    useEmployeeEducation,
    useEmployeePreviousEmployment,
    useEmployeeDocuments,
    useEmployeeTimeline,
} from './use-hr-queries';

export {
    useCreateDepartment,
    useUpdateDepartment,
    useDeleteDepartment,
    useCreateDesignation,
    useUpdateDesignation,
    useDeleteDesignation,
    useCreateGrade,
    useUpdateGrade,
    useDeleteGrade,
    useCreateEmployeeType,
    useUpdateEmployeeType,
    useDeleteEmployeeType,
    useCreateCostCentre,
    useUpdateCostCentre,
    useDeleteCostCentre,
    useCreateEmployee,
    useUpdateEmployee,
    useDeleteEmployee,
    useUpdateEmployeeStatus,
    useCreateNominee,
    useUpdateNominee,
    useDeleteNominee,
    useCreateEducation,
    useUpdateEducation,
    useDeleteEducation,
    useCreatePreviousEmployment,
    useUpdatePreviousEmployment,
    useDeletePreviousEmployment,
    useCreateDocument,
    useUpdateDocument,
    useDeleteDocument,
} from './use-hr-mutations';

// Attendance
export {
    attendanceKeys,
    useAttendanceRecords,
    useAttendanceRecord,
    useAttendanceSummary,
    useAttendanceRules,
    useAttendanceOverrides,
    useHolidays,
    useRosters,
    useOvertimeRules,
} from './use-attendance-queries';

export {
    useCreateAttendanceRecord,
    useUpdateAttendanceRecord,
    useUpdateAttendanceRules,
    useCreateAttendanceOverride,
    useUpdateAttendanceOverride,
    useCreateHoliday,
    useUpdateHoliday,
    useDeleteHoliday,
    useCloneHolidays,
    useCreateRoster,
    useUpdateRoster,
    useDeleteRoster,
    useUpdateOvertimeRules,
} from './use-attendance-mutations';

// Leave Management
export {
    leaveKeys,
    useLeaveTypes,
    useLeaveType,
    useLeavePolicies,
    useLeaveBalances,
    useLeaveRequests,
    useLeaveRequest,
    useLeaveSummary,
} from './use-leave-queries';

export {
    useCreateLeaveType,
    useUpdateLeaveType,
    useDeleteLeaveType,
    useCreateLeavePolicy,
    useUpdateLeavePolicy,
    useDeleteLeavePolicy,
    useAdjustLeaveBalance,
    useInitializeLeaveBalances,
    useCreateLeaveRequest,
    useApproveLeaveRequest,
    useRejectLeaveRequest,
    useCancelLeaveRequest,
} from './use-leave-mutations';

// Payroll & Compliance
export {
    payrollKeys,
    useSalaryComponents,
    useSalaryComponent,
    useSalaryStructures,
    useSalaryStructure,
    useEmployeeSalaries,
    useEmployeeSalary,
    usePFConfig,
    useESIConfig,
    usePTConfigs,
    useGratuityConfig,
    useBonusConfig,
    useLWFConfigs,
    useBankConfig,
    useLoanPolicies,
    useLoanPolicy,
    useLoans,
    useTaxConfig,
} from './use-payroll-queries';

export {
    useCreateSalaryComponent,
    useUpdateSalaryComponent,
    useDeleteSalaryComponent,
    useCreateSalaryStructure,
    useUpdateSalaryStructure,
    useDeleteSalaryStructure,
    useAssignEmployeeSalary,
    useUpdateEmployeeSalary,
    useUpdatePFConfig,
    useUpdateESIConfig,
    useCreatePTConfig,
    useUpdatePTConfig,
    useDeletePTConfig,
    useUpdateGratuityConfig,
    useUpdateBonusConfig,
    useCreateLWFConfig,
    useUpdateLWFConfig,
    useDeleteLWFConfig,
    useUpdateBankConfig,
    useCreateLoanPolicy,
    useUpdateLoanPolicy,
    useDeleteLoanPolicy,
    useCreateLoan,
    useUpdateLoan,
    useUpdateLoanStatus,
    useUpdateTaxConfig,
} from './use-payroll-mutations';

// Payroll Operations (Runs, Payslips, Holds, Revisions, Statutory, Reports)
export {
    payrollRunKeys,
    usePayrollRuns,
    usePayrollRun,
    usePayrollEntries,
    usePayrollEntry,
    usePayslips,
    usePayslip,
    useSalaryHolds,
    useSalaryRevisions,
    useSalaryRevision,
    useArrearEntries,
    useStatutoryFilings,
    useStatutoryDashboard,
    useSalaryRegister,
    useBankFile,
    usePFECR,
    useESIChallan,
    usePTChallan,
    useVarianceReport,
} from './use-payroll-run-queries';

export {
    useCreatePayrollRun,
    useLockAttendance,
    useReviewExceptions,
    useComputeSalaries,
    useComputeStatutory,
    useApproveRun,
    useDisburseRun,
    useOverridePayrollEntry,
    useEmailPayslip,
    useGeneratePayslips,
    useCreateSalaryHold,
    useReleaseSalaryHold,
    useCreateSalaryRevision,
    useApproveSalaryRevision,
    useApplySalaryRevision,
    useCreateStatutoryFiling,
    useUpdateStatutoryFiling,
} from './use-payroll-run-mutations';

// ESS & Workflows
export {
    essKeys,
    useEssConfig,
    useApprovalWorkflows,
    useApprovalWorkflow,
    useApprovalRequests,
    useApprovalRequest,
    usePendingApprovals,
    useNotificationTemplates,
    useNotificationRules,
    useITDeclarations,
    useITDeclaration,
    useMyProfile,
    useMyPayslips,
    useMyLeaveBalance,
    useMyAttendance,
    useMyDeclarations,
    useTeamMembers,
    usePendingMssApprovals,
    useTeamAttendance,
    useTeamLeaveCalendar,
} from './use-ess-queries';

export {
    useUpdateEssConfig,
    useCreateApprovalWorkflow,
    useUpdateApprovalWorkflow,
    useDeleteApprovalWorkflow,
    useApproveRequest,
    useRejectRequest,
    useCreateNotificationTemplate,
    useUpdateNotificationTemplate,
    useDeleteNotificationTemplate,
    useCreateNotificationRule,
    useUpdateNotificationRule,
    useDeleteNotificationRule,
    useCreateITDeclaration,
    useUpdateITDeclaration,
    useSubmitITDeclaration,
    useVerifyITDeclaration,
    useLockITDeclaration,
    useApplyLeave,
    useRegularizeAttendance,
} from './use-ess-mutations';

// Performance Management
export {
    performanceKeys,
    useAppraisalCycles,
    useAppraisalCycle,
    useGoals,
    useGoal,
    useDepartmentGoals,
    useAppraisalEntries,
    useAppraisalEntry,
    useCalibrationData,
    useFeedback360List,
    useFeedback360,
    useFeedback360Report,
    useSkills,
    useSkill,
    useSkillMappings,
    useSkillGapAnalysis,
    useSuccessionPlans,
    useSuccessionPlan,
    useNineBoxData,
    useBenchStrength,
    usePerformanceDashboard,
} from './use-performance-queries';

export {
    useCreateAppraisalCycle,
    useUpdateAppraisalCycle,
    useDeleteAppraisalCycle,
    useActivateAppraisalCycle,
    usePublishAppraisalCycle,
    useCloseAppraisalCycle,
    useCreateGoal,
    useUpdateGoal,
    useDeleteGoal,
    useUpdateAppraisalEntry,
    useSubmitSelfReview,
    useSubmitManagerReview,
    usePublishAppraisalEntry,
    useCreateFeedback360,
    useUpdateFeedback360,
    useCreateSkill,
    useUpdateSkill,
    useDeleteSkill,
    useCreateSkillMapping,
    useUpdateSkillMapping,
    useDeleteSkillMapping,
    useCreateSuccessionPlan,
    useUpdateSuccessionPlan,
    useDeleteSuccessionPlan,
} from './use-performance-mutations';

// Recruitment, Training & Advanced HR
export {
    recruitmentKeys,
    useRequisitions,
    useRequisition,
    useCandidates,
    useCandidate,
    useInterviews,
    useInterview,
    useRecruitmentDashboard,
    useTrainingCatalogue,
    useTrainingCatalogueItem,
    useTrainingNominations,
    useTrainingDashboard,
    useAssetCategories,
    useAssetCategory,
    useAssets,
    useAsset,
    useAssetAssignments,
    useExpenseClaims,
    useExpenseClaim,
    useLetterTemplates,
    useLetterTemplate,
    useLetters,
    useLetter,
    useGrievanceCategories,
    useGrievanceCategory,
    useGrievanceCases,
    useGrievanceCase,
    useDisciplinaryActions,
    useDisciplinaryAction,
} from './use-recruitment-queries';

export {
    useCreateRequisition,
    useUpdateRequisition,
    useDeleteRequisition,
    useCreateCandidate,
    useUpdateCandidate,
    useCreateInterview,
    useUpdateInterview,
    useCreateTrainingCatalogue,
    useUpdateTrainingCatalogue,
    useDeleteTrainingCatalogue,
    useCreateTrainingNomination,
    useUpdateTrainingNomination,
    useCreateAssetCategory,
    useUpdateAssetCategory,
    useDeleteAssetCategory,
    useCreateAsset,
    useUpdateAsset,
    useCreateAssetAssignment,
    useUpdateAssetAssignment,
    useCreateExpenseClaim,
    useUpdateExpenseClaim,
    useApproveExpenseClaim,
    useRejectExpenseClaim,
    useCreateLetterTemplate,
    useUpdateLetterTemplate,
    useDeleteLetterTemplate,
    useCreateLetter,
    useGenerateLetterPdf,
    useCreateGrievanceCategory,
    useUpdateGrievanceCategory,
    useDeleteGrievanceCategory,
    useCreateGrievanceCase,
    useUpdateGrievanceCase,
    useCreateDisciplinaryAction,
    useUpdateDisciplinaryAction,
} from './use-recruitment-mutations';

// Offboarding (Exit & Separation)
export {
    offboardingKeys,
    useExitRequests,
    useExitRequest,
    useExitClearances,
    useExitInterview,
    useFnFSettlements,
    useFnFSettlement,
} from './use-offboarding-queries';

export {
    useCreateExitRequest,
    useUpdateExitRequest,
    useUpdateClearance,
    useCreateExitInterview,
    useComputeFnF,
    useApproveFnF,
    usePayFnF,
} from './use-offboarding-mutations';

// Transfer, Promotion & Delegation
export {
    transferKeys,
    useTransfers,
    useTransfer,
    usePromotions,
    usePromotion,
    useDelegates,
} from './use-transfer-queries';

export {
    useCreateTransfer,
    useApproveTransfer,
    useApplyTransfer,
    useRejectTransfer,
    useCancelTransfer,
    useCreatePromotion,
    useApprovePromotion,
    useApplyPromotion,
    useRejectPromotion,
    useCancelPromotion,
    useCreateDelegate,
    useRevokeDelegate,
} from './use-transfer-mutations';

// Support & Module CRUD
export {
    useSupportTickets,
    useSupportTicket,
} from './use-company-admin-queries';

export {
    useCreateSupportTicket,
    useSendSupportMessage,
    useCloseSupportTicket,
    useAddLocationModules,
    useRemoveLocationModule,
} from './use-company-admin-mutations';
