export {
    companyAdminKeys,
    useCompanyProfile,
    useCompanyLocations,
    useCompanyLocation,
    useCompanyShifts,
    useCompanyContacts,
    useCompanyNoSeries,
    useCompanyIOTReasons,
    useCompanyControls,
    useCompanySettings,
    useCompanyUsers,
    useCompanyUser,
    useCompanyAuditLogs,
    useCompanyActivity,
} from './use-company-admin-queries';

export {
    useUpdateProfileSection,
    useUpdateLocation,
    useDeleteLocation,
    useCreateShift,
    useUpdateShift,
    useDeleteShift,
    useCreateContact,
    useUpdateContact,
    useDeleteContact,
    useCreateNoSeries,
    useUpdateNoSeries,
    useDeleteNoSeries,
    useCreateIOTReason,
    useUpdateIOTReason,
    useDeleteIOTReason,
    useUpdateControls,
    useUpdateSettings,
    useCreateUser,
    useUpdateUser,
    useUpdateUserStatus,
} from './use-company-admin-mutations';

export {
    hrKeys,
    useDepartments,
    useDepartment,
    useDesignations,
    useDesignation,
    useGrades,
    useGrade,
    useEmployeeTypes,
    useEmployeeType,
    useCostCentres,
    useCostCentre,
    useEmployees,
    useEmployee,
    useEmployeeNominees,
    useEmployeeEducation,
    useEmployeePreviousEmployment,
    useEmployeeDocuments,
    useEmployeeTimeline,
} from './use-hr-queries';

export {
    useCreateDepartment,
    useUpdateDepartment,
    useDeleteDepartment,
    useCreateDesignation,
    useUpdateDesignation,
    useDeleteDesignation,
    useCreateGrade,
    useUpdateGrade,
    useDeleteGrade,
    useCreateEmployeeType,
    useUpdateEmployeeType,
    useDeleteEmployeeType,
    useCreateCostCentre,
    useUpdateCostCentre,
    useDeleteCostCentre,
    useCreateEmployee,
    useUpdateEmployee,
    useDeleteEmployee,
    useUpdateEmployeeStatus,
    useCreateNominee,
    useUpdateNominee,
    useDeleteNominee,
    useCreateEducation,
    useUpdateEducation,
    useDeleteEducation,
    useCreatePreviousEmployment,
    useUpdatePreviousEmployment,
    useDeletePreviousEmployment,
    useCreateDocument,
    useUpdateDocument,
    useDeleteDocument,
} from './use-hr-mutations';
